site_name: Nvim-Toolkit
site_description: Shared runtime utilities library for Neovim plugins and configurations
site_url: https://greggh.github.io/nvim-toolkit/
repo_url: https://github.com/greggh/nvim-toolkit
repo_name: greggh/nvim-toolkit

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

nav:
  - Home: index.md
  - Usage:
      - Getting Started: usage/getting-started.md
      - Examples: usage/examples.md
  - Modules:
      - UI: modules/ui.md
      - Log: modules/log.md
      - Filesystem: modules/fs.md
      - API: modules/api.md
      - Config: modules/config.md
      - Keymap: modules/keymap.md
  - Contributing: contributing.md
  - Changelog: changelog.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - footnotes
  - attr_list
  - md_in_html

plugins:
  - search